server:
  port: 8083
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.207.250:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


    producer:
      bootstrap-servers: 192.168.207.250:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer

      properties:
        spring:
          json:
            add:
              type:
                headers: false



